### ISSUE TITLE
zlib-1.2.11 is no longer available from zlib.net

### ISSUE THREAD

**Issue by wwkeyboard** [fwup-home/fwup#187]
http://zlib.net/ bumped their version to 1.2.12 (http://madler.net/pipermail/zlib-announce_madler.net/2022/000012.html) and removed the old zip. This means download_deps.sh fails to download the file. Two possible solutions:

1. change download_deps.sh to point to the zlib asset hosted on github, as it does with confuse
2. update zlib to 1.2.12

**Comment by wwkeyboard** [comment]
@fhunleth has proposed solution #2 in #188

**Comment by fhunleth** [comment]
@wwkeyboard Hi @wwkeyboard! Thanks for letting me know about this. I see that you saw my PR.

**Comment by fhunleth** [comment]
Fixed in #188.
