### ISSUE TITLE
Compiling with glibc 2.36 fails due to conflicting headers

### ISSUE THREAD

**Issue by linusdm** [fwup-home/fwup#192]
Running `make` with a recent glibc 2.36 (tested on a new Linux Manjaro installation, version `21.3.7`) fails. As far as I can see this is due to conflicting headers in [`src/mmc_linux.c`](https://github.com/fwup-home/fwup/blob/a8cac490aaaeb32334346197176e1e74d4c94d9c/src/mmc_linux.c).

As stated in the [changelog of glibc 2.36](https://sourceware.org/glibc/wiki/Release/2.36#Usage_of_.3Clinux.2Fmount.h.3E_and_.3Csys.2Fmount.h.3E), `<linux/mount.h>` and `<sys/mount.h>` are conflicting. `<linux/mount.h>` is imported indirectly by `<linux/fs.h>` [here](https://github.com/fwup-home/fwup/blob/main/src/mmc_linux.c#L38), while `<sys/mount.h>` is imported directly [here](https://github.com/fwup-home/fwup/blob/main/src/mmc_linux.c#L25).

Uncommenting the import of `<sys/mount.h>` in `mmc_linux.c` fixes running make, and running `make check` passes all tests. But I'm not sure if this can be done without any side effects or missing functionality later on.

Also note that the same import of `<sys/mount.h>` is found in [`src/mmc_bsd.c`](https://github.com/fwup-home/fwup/blob/3e3fd80edf50b32ae7e303f731431c53b7079bc0/src/mmc_bsd.c), and might have the same issue.

**Comment by fhunleth** [comment]
Thanks for tracking this down! It sounds like the fix is straightforward, but I'll take a look today and see if I can get an updated patch release out soon.
