### ISSUE TITLE
Support delta-source-fat-offset and delta-source-fat-path

### ISSUE THREAD

**Issue by jeanparpaillon** [fwup-home/fwup#201]
Delta upgrades do not support applying delta on FAT files, zImage on boot partition for many devices, precisely.

Supporting delta-source-fat-offset and delta-source-fat-path is needed for applying delta upgrades on FAT files.

**Comment by jeanparpaillon** [comment]
@fhunleth thanks for looking at it. 
With my version of the code, I got the following error when trying to apply a patch:
"target window checksum mismatch"
The condition for reaching this message is quite obscure for me (https://github.com/fwup-home/fwup/blob/main/src/3rdparty/xdelta3/xdelta3-decode.h#L799 )
Any idea on what may be wrong ?

**Comment by fhunleth** [comment]
Whenever I've gotten an xdelta3 error, it's either been that I had a different source file on the target than what I thought that I should have had or a bug with reading the xdelta3 file, or source data. 

Is there any way I can take a look?

Also, I have no reason to believe that `main` would behave different than your version of the code, but did you try that?

**Comment by fhunleth** [comment]
Great! Thank you for the update.
