### ISSUE TITLE
Arm build is missing from releases.

### ISSUE THREAD

**Issue by jessearmstrong** [fwup-home/fwup#213]
Trying to get a copy off the fwup for use on an armbian machine, but the release appears to be missing. The link in the Installation section of the Readme is 404.

https://github.com/fwup-home/fwup/releases/download/v1.10.0/fwup_1.10.0_armhf.deb

**Comment by fhunleth** [comment]
Thanks for letting me know! Turns out that the file was still in the CI artifacts folder from the release build. The link should work now.
