### ISSUE TITLE
Suggestion: Ignore tiny discovered drives/devices

### ISSUE THREAD

**Issue by lawik** [fwup-home/fwup#222]
I have an audio interface plugged into my main machine and it exposes a very small mass storage device with a manual and maybe a driver on it. It shows in fwup as 0.0GiB. It would be neat if this was just disregarded. Maybe anything under 0.1GiB or similar?

**Comment by fhunleth** [comment]
How big is the audio interface device? Could you run `fwup -D` to get a more precise size. Setting a lower bound definitely seems like a good idea. I just need to do some checking if it's set to 100 MiB since that vaguely seems like something I've seen.

**Comment by lawik** [comment]
```
/dev/sdb,196608

Scarlett Welcome Disk (0.10)
Y8PPD2D0B5D4DA
197 KB (196,608 bytes)
```

**Comment by fhunleth** [comment]
@lawik Could you try out the PR? Build instructions are at https://github.com/fwup-home/fwup/blob/main/docs/build_osx.md#building-and-installing-with-homebrew.

**Comment by lawik** [comment]
Will do. But brave to assume I do my AV work on a Mac :D I am way more foolish and will test it on Linux thank you very mich 💖
