### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jbnoblot** [fwup-home/fwup#235]
Hello team, 
I am very sorry for this poor ticket 
I am not very familiar with autogen/configure but I try to run clang analyzer on it
I found this (not with clang but gcc --analyzer)
`CFLAGS="-Wall -Wextra -pedantic" ./configure && make` give me 
[Wextra.txt](https://github.com/user-attachments/files/17508849/Wextra.txt)

`CFLAGS="--analyzer" ./configure && make` give me 
[analyzer.txt](https://github.com/user-attachments/files/17508882/analyzer.txt)

I don't know how to run sanitizer with autogen/configure and it's out of my C level ^^

**Comment by fhunleth** [comment]
You don't need to run the clang analyzer to use `fwup`. 

However, if you really want to do this, you need to tell clang which analyzer to run. Please take a look at the clang manual. There's a lot of information there on static analysis, and I'd recommend learning how to use it on a simpler project first before trying it on `fwup`.
